name: Daily StackOverflow Python Question

on:
  schedule:
    # هر روز ساعت 10 صبح UTC
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  get_question:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Run Python script
      run: |
        python3 get_question.py
